baseURL = ""
languageCode = "en-us"
title = "Navigator | Responsive Multipurpose Bootstrap Hugo Template"
theme = "navigator hugo"
summaryLength = 10
enableRobotsTXT = true
googleAnalytics = ""
enableGitInfo = false
pygmentsCodeFences = true
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"
themesDir = "themes"
publishDir = "public"

[params]
logo = "images/logo.png"

  [params.cookies]
  enable = true
  expire_days = 2

[[Params.listeLangues]]
code = "fr"

[[Params.listeLangues]]
code = "en"
author = "Themefisher"
description = "This is meta description"

[Languages.fr]
weight = 1
languageCode = "fr-fr"
title = "FRANCAIS Example site multi-language"
dateFormat = "2 January 2006"
home = "FR Home"
logo = "images/logo.png"
menufixed = false
footerDescription = "FRANCAIS Integer posuere erat a ante venenati dapibus posuere velit aliquet. Fusce dapibus, tellus cursus commodo, tortor mauris sed posuere."
footerServiceTitle = "FRANCAIS Services"
footerQuicklinkTitle = "FRANCAIS Quick links"
footerAboutTitle = "FRANCAIS About"
footerSubscribeTitle = "FRANCAIS Subscribe"

[Languages.fr.params.hero]
enable = true
heading = "FRANCAIS We love to make brands grow"
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At quo dolor est incidunt suscipit minima, alias numquam voluptatum rerum porro. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore at laboriosam unde repellat id expedita quae quisquam libero officia consequatur."
button = true
btnText = "Know More"
btnURL = "https://themefisher.com/"
videoThumb = "images/slider/video-player-thumb.jpg"
videoURL = "https://www.youtube.com/embed/g3-VxLQO7do"

[Languages.fr.params.aboutSm]
enable = true
title = "FRANCAIS We have explored the digital landscape with passion for a long time"
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae deleniti ipsa labore necessitatibus culpa veritatis quo accusantium, neque enim ea ad eaque iure, quas tempore velit, quibusdam dolor illo! Explicabo. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid quisquam maiores iste soluta, nihil dolorem?"

[Languages.fr.params.blog]
enable = true
topTitle = "OUR UNTOLD STORY"
title = "FRANCAIS Blog."
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

[Languages.fr.params.contact]
enable = true
topTitle = "DROP US A NOTE"
title = "FRANCAIS Contact Us."
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
address = "14/05, Stockhome <br> Victori Palace , United States"
phone = "(03) 9283 2617"
fax = "+61 3827 3590"
facebook = "https://www.facebook.com/"
twitter = "https://twitter.com/"
linkedin = "https://www.linkedin.com/"
dribbble = "https://dribbble.com/"
instagram = "https://www.instagram.com/"
mapLatitude = "51.507351"
mapLongitude = "-0.127758"
mapMarker = "images/marker.png"

[Languages.fr.params.cta]
enable = true
bg = "images/call-to-action/call-to-action-bg-2.jpg"
title = "FRANCAIS Let's Create Something Together"
subtitle = "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
btnText = "Nous contacter"

[Languages.en]
weight = 2
languageCode = "en-us"
title = "Example site multi-language"
dateFormat = "January 2, 2006"
home = "EN Home"
logo = "images/logo.png"
menufixed = false
footerDescription = "Integer posuere erat a ante venenati dapibus posuere velit aliquet. Fusce dapibus, tellus cursus commodo, tortor mauris sed posuere."
footerServiceTitle = "Service"
footerQuicklinkTitle = "Quicklinks"
footerAboutTitle = "About"
footerSubscribeTitle = "Subscribe"

[Languages.en.params.hero]
enable = true
heading = "We love to make brands grow"
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At quo dolor est incidunt suscipit minima, alias numquam voluptatum rerum porro. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore at laboriosam unde repellat id expedita quae quisquam libero officia consequatur."
button = true
btnText = "Know More"
btnURL = "https://themefisher.com/"
videoThumb = "images/slider/video-player-thumb.jpg"
videoURL = "https://www.youtube.com/embed/g3-VxLQO7do"

[Languages.en.params.aboutSm]
enable = true
title = "We have explored the digital landscape with passion for a long time"
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae deleniti ipsa labore necessitatibus culpa veritatis quo accusantium, neque enim ea ad eaque iure, quas tempore velit, quibusdam dolor illo! Explicabo. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid quisquam maiores iste soluta, nihil dolorem?"

[Languages.en.params.blog]
enable = true
topTitle = "OUR UNTOLD STORY"
title = "Blog."
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

[Languages.en.params.contact]
enable = true
topTitle = "DROP US A NOTE"
title = "Contact Us."
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
address = "14/05, Stockhome <br> Victori Palace , United States"
phone = "(03) 9283 2617"
fax = "+61 3827 3590"
facebook = "https://www.facebook.com/"
twitter = "https://twitter.com/"
linkedin = "https://www.linkedin.com/"
dribbble = "https://dribbble.com/"
instagram = "https://www.instagram.com/"
mapLatitude = "51.507351"
mapLongitude = "-0.127758"
mapMarker = "images/marker.png"

[Languages.en.params.cta]
enable = true
bg = "images/call-to-action/call-to-action-bg-2.jpg"
title = "Let's Create Something Together"
subtitle = "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
btnText = "Contact Us"

[[menu.nav]]
name = "about"
url = "about"
weight = 2

[[menu.nav]]
name = "service"
url = "service"
weight = 3

[[menu.nav]]
name = "portfolio"
url = "portfolio"
weight = 4

[[menu.nav]]
name = "blog"
url = "blog"
weight = 5

[[menu.nav]]
name = "contact"
url = "contact"
weight = 6

[[menu.service]]
name = "graphicdesign"
url = "service"
weight = 1

[[menu.service]]
name = "webdesign"
url = "service"
weight = 2

[[menu.service]]
name = "webdevelopment"
url = "service"
weight = 3

[[menu.quicklink]]
name = "partners"
url = "about"
weight = 1

[[menu.quicklink]]
name = "about"
url = "about"
weight = 2

[[menu.quicklink]]
name = "faqs"
url = "about"
weight = 3

[[menu.quicklink]]
name = "badges"
url = "about"
weight = 4
